### ISSUE TITLE
How can I build and deploy it?

### ISSUE THREAD

**Issue by rain1024** [dominhhai/dominhhai.github.io#8]
Firstly, your blog is very nice with excellent contents. It is very useful for me. Thank you so much for creating it.

Secondly, I just fork your blog in my own repository. How can I build and deploy it in my own page, such as rain1024.github.io? I can't find any instruction about it in your README

**Comment by dominhhai** [comment]
Please  check the `Makefile` file.

**Comment by rain1024** [comment]
Thank you, I will check it
